config/routes.rb
Rails.application.routes.draw do
  root :to => "companies#index"

  resources :companies, :only => [:index, :show, :create, :destroy, :new]
  resources :employees, :only => [:index, :show, :create, :destroy, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord

    validates :name, presence: true

    has_many :sub_companies, class_name: "Company", foreign_key: "parent_id", dependent: :destroy
    belongs_to :parent, class_name: "Company", optional: true

    has_many :employees, dependent: :destroy

    def all_sub_companies(subs = [])
        subs += sub_companies
        sub_companies.each do |company|
            return company.all_sub_companies(subs)
        end
        return subs
    end

    def employees_count
        employees.size
    end

    def total_employees_count
        all_sub_companies.inject(employees_count){|sum, company| sum + company.employees_count }
    end


end

app/models/employee.rb
class Employee < ApplicationRecord

    validates :name, presence: true
    validates :company_id, presence: true
    belongs_to :company

end

app/controllers/CompaniesController.rb
class CompaniesController < ApplicationController

    def index
        @companies = Company.all
    end

    def show
        @company = Company.find_by_id(params[:id])
    end

    def create
        cp = Company.create(name: params[:name])
        redirect_to cp
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

    def index
        @companies = Company.all
        if params[:employees_count]
            @companies = @companies.filter{ |c| c.total_employees_count < params[:employees_count].to_i }
        end
    end

    def new
        @company = Company.new
    end

    def show
        @company = Company.find(params[:id])
    end

    def create
        @company = Company.new(company_params)
        if @company.save
            redirect_to @company
        else
            render 'new', status: :unprocessable_entity
        end
    end


    def destroy
        company = Company.find(params[:id])
        company.destroy
        redirect_to companies_path
    end

    def company_params
        params.require(:company).permit(:name, :parent_id)
    end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

    def index
        @employees = Employee.all
    end

    def new
        @employee = Employee.new
    end

    def show
        @employee = Employee.find(params[:id])
    end

    def create
        @employee = Employee.new(employee_params)
        if @employee.save
            redirect_to @employee
        else
            render 'new', status: :unprocessable_entity
        end
    end


    def destroy
        employee = Employee.find(params[:id])
        employee.destroy
        redirect_to employees_path
    end

    def employee_params
        params.require(:employee).permit(:name, :company_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/companies/index.html.erb
<%= form_with url: "/companies", method: :get do |form| %>
  <%= form.label :employees_count, "Required amount of employees:" %>
  <%= form.text_field :employees_count %>
  <%= form.submit "Search" %>
<% end %>

<ul>
  <% @companies.each do |company| %> 
    <li>
      <div><%= company.name %> => <%=link_to('Show', company_path(company)) %> - <%= link_to "Delete", company_path(company), :confirm => "Are you sure?", :method => :delete %></div>
    </li>
  <% end %>
</ul>

app/views/companies/new.html.erb
<%= form_for @company, :url => {:action => :create} do |form| %>
  <% @company.errors.full_messages.each do |message| %>
    <div><%= message %></div>
  <% end %>
  <%= form.label :name, "Company name:" %>
  <%= form.text_field :name %>
  <%= form.label :parent_id, "Parent Company:" %>
  <%= form.select :parent_id, options_from_collection_for_select(Company.all, 'id', 'name') %>
  <%= form.submit "Submit" %>
<% end %>

app/views/companies/show.html.erb
<div>Name: <%= @company.name %></div>
<div>Sub companies:
<ul>
      <% @company.all_sub_companies.each do |company| %> 
        <li>
          <div><%= company.name %> => <%=link_to('Show', company_path(company)) %></div>
        </li>
      <% end %>
    </ul>
</div>
<div>Employees:
<ul>
      <% @company.employees.each do |employee| %> 
        <li>
          <div><%= employee.name %> => <%=link_to('Show', employee_path(employee)) %></div>
        </li>
      <% end %>
    </ul>
</div>

app/views/employees/index.html.erb
<ul>
  <% @employees.each do |employee| %> 
    <li>
      <div><%= employee.name %> => <%=link_to('Show', employee_path(employee)) %> - <%= link_to "Delete", employee_path(employee), :confirm => "Are you sure?", :method => :delete %></div>
    </li>
  <% end %>
</ul>
  

app/views/employees/new.html.erb
<%= form_for @employee, :url => {:action => :create} do |form| %>
  <% @employee.errors.full_messages.each do |message| %>
    <div><%= message %></div>
  <% end %>
  <%= form.label :name, "Employee name:" %>
  <%= form.text_field :name %>
  <%= form.label :company_id, "Company:" %>
  <%= form.select :company_id, options_from_collection_for_select(Company.all, 'id', 'name') %>
  <%= form.submit "Submit" %>
<% end %>

app/views/employees/show.html.erb
<div>Name: <%= @employee.name %></div>
<div>Company: <%= @employee.company.name %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shyftplan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li><%= link_to("Companies", companies_path) %></li>
      <li><%= link_to("New Company", new_company_path) %></li>
      <li><%= link_to("Employee", employees_path) %></li>
      <li><%= link_to("New Employee", new_employee_path) %></li> 
    </ul>
    <hr/>
    <%= yield %>
  </body>
</html>